// AI 도구 데이터
const toolsData = [
  {
    id: 'copilot',
    name: 'Microsoft Copilot',
    category: 'llm',
    educator: true,
    educatorBadge: '교수/교사 가능',
    cost: '무료 (M365 Edu)',
    originalPrice: '$30/mo',
    optimized: 'MS Office 문서 자동화 & 생태계 통합',
    purpose: '워드/PPT 초안 작성, 엑셀 데이터 분석, 이메일 요약',
    method: '학교 계정(@ac.kr, @edu)으로 로그인 시 자동 적용',
    tags: ['무료', '오피스'],
    url: 'https://www.microsoft.com/ko-kr/education/products/microsoft-365',
    buttonText: '할인 확인하기'
  },
  {
    id: 'gemini',
    name: 'Google Gemini',
    category: 'llm',
    educator: false,
    cost: '기본 무료',
    originalPrice: 'Adv $20',
    optimized: '구글 워크스페이스 연동 & 멀티모달 분석',
    purpose: '유튜브 영상 요약, 이미지 분석, 드라이브 문서 검색',
    method: '구글 계정 가입 (별도 교육자 할인 요금제 없음)',
    tags: ['무료', '멀티모달'],
    url: 'https://gemini.google.com/',
    buttonText: '서비스 바로가기'
  },
  {
    id: 'gemini-pro',
    name: 'Google Gemini Pro',
    category: 'llm',
    educator: true,
    educatorBadge: '학생 무료 1년',
    cost: '무료 (학생 1년)',
    originalPrice: '$200/년',
    optimized: '최고급 AI 모델 & 2TB 저장공간 & 비디오 생성',
    purpose: '고급 AI 연구, Deep Research, NotebookLM, Veo 3 비디오 생성',
    method: '미국/일본/인도네시아/한국/브라질 대학생, gemini.google/students에서 신청',
    tags: ['무료', '프리미엄', '학생'],
    url: 'https://gemini.google/students/',
    buttonText: '학생 무료 신청'
  },
  {
    id: 'chatgpt-teachers',
    name: 'ChatGPT for Teachers',
    category: 'llm',
    educator: true,
    educatorBadge: '교사 무료',
    cost: '무료 (K-12 교사)',
    originalPrice: 'Plus $20',
    optimized: '교육용 보안 & FERPA 준수 & 무제한 GPT-4.1',
    purpose: '수업 자료 작성, 학생 피드백 생성, 안전한 AI 협업 공간',
    method: '미국 K-12 교사 인증 (2027년 6월까지 무료)',
    tags: ['무료', '교육', '보안'],
    url: 'https://openai.com/index/chatgpt-for-teachers/',
    buttonText: '교사 무료 신청'
  },
  {
    id: 'consensus',
    name: 'Consensus',
    category: 'research',
    educator: true,
    educatorBadge: '교수/교사 가능',
    cost: '$7.19/mo',
    originalPrice: '$11.99',
    optimized: '근거 기반(Evidence-Based) 학술 답변',
    purpose: '신뢰도 높은 논문 인용, 과학적 질문에 대한 답변 도출',
    method: 'ac.kr/edu 메일 가입 (교수진도 할인/무료 트라이얼)',
    tags: ['할인', '논문검색'],
    url: 'https://consensus.app/pricing/',
    buttonText: '할인 확인하기'
  },
  {
    id: 'semantic-scholar',
    name: 'Semantic Scholar',
    category: 'research',
    educator: true,
    educatorBadge: '전체 무료',
    cost: '완전 무료',
    originalPrice: null,
    optimized: '광범위한 과학 논문 탐색 및 인용 분석',
    purpose: '최신 연구 트렌드 파악, 연관 논문 검색',
    method: '연구자/학생 구분 없이 즉시 사용 가능',
    tags: ['무료', '논문검색'],
    url: 'https://www.semanticscholar.org/',
    buttonText: '서비스 바로가기'
  },
  {
    id: 'perplexity',
    name: 'Perplexity AI',
    category: 'research',
    educator: false,
    cost: '기본 무료',
    originalPrice: 'Pro $20',
    optimized: '실시간 정보 접근 & 정확한 출처 인용',
    purpose: '최신 정보 검색, 논문 작성 보조, 팩트 체크',
    method: '무료 계정 가입 (Pro는 유료)',
    tags: ['무료', '검색', '인용'],
    url: 'https://www.perplexity.ai/',
    buttonText: '서비스 바로가기'
  },
  {
    id: 'notebooklm',
    name: 'NotebookLM',
    category: 'research',
    educator: false,
    cost: '무료',
    originalPrice: null,
    optimized: '문서 업로드 & 요약 & 오디오 생성',
    purpose: '논문 요약, 학습 가이드 생성, 오디오 개요',
    method: '구글 계정으로 무료 사용',
    tags: ['무료', '문서분석'],
    url: 'https://notebooklm.google.com/',
    buttonText: '서비스 바로가기'
  },
  {
    id: 'adobe',
    name: 'Adobe CC',
    category: 'design',
    educator: true,
    educatorBadge: '교수/교사 가능',
    cost: '~60% OFF',
    originalPrice: '$54.99',
    optimized: '전문가급 크리에이티브 콘텐츠 제작',
    purpose: '사진/영상 편집, 그래픽 디자인, PDF 편집',
    method: '학교 이메일 또는 재직 증명서(교사)로 인증',
    tags: ['할인', '디자인', '영상편집'],
    url: 'https://www.adobe.com/kr/creativecloud/buy/students.html',
    buttonText: '할인 확인하기'
  },
  {
    id: 'figma',
    name: 'Figma',
    category: 'design',
    educator: true,
    educatorBadge: '교수/교사 가능',
    cost: '무료 (Edu plan)',
    originalPrice: 'Pro',
    optimized: '실시간 협업 디자인 및 수업용 화이트보드',
    purpose: 'UI/UX 실습, FigJam을 활용한 아이디어 브레인스토밍',
    method: 'Figma Education에서 교사(Educator)로 승인 신청',
    tags: ['무료', '디자인', '협업'],
    url: 'https://www.figma.com/education/',
    buttonText: '교육용 무료 신청'
  },
  {
    id: 'canva',
    name: 'Canva',
    category: 'design',
    educator: true,
    educatorBadge: '교사 무료',
    cost: '무료 (교육용)',
    originalPrice: 'Pro $15',
    optimized: 'AI 디자인 도구 & 템플릿 & 프레젠테이션',
    purpose: '수업 자료 제작, 포스터 디자인, AI 이미지 생성',
    method: 'Canva for Education에서 교사 인증',
    tags: ['무료', '디자인', 'AI생성'],
    url: 'https://www.canva.com/education/',
    buttonText: '교육용 신청'
  },
  {
    id: 'github',
    name: 'GitHub Education',
    category: 'coding',
    educator: true,
    educatorBadge: '교사 툴박스',
    cost: '무료',
    originalPrice: 'Team/Ent',
    optimized: '개발자 도구 번들 & 수업 관리(Classroom)',
    purpose: '학생: Student Pack / 교수: Teacher Toolbox (수업관리 등)',
    method: '교수진 ID/재직증명서로 Teacher 인증 신청',
    tags: ['무료', '코딩', '번들'],
    url: 'https://education.github.com/teachers',
    buttonText: 'Teacher 신청하기'
  },
  {
    id: 'jetbrains',
    name: 'JetBrains',
    category: 'coding',
    educator: true,
    educatorBadge: '교수/교사 가능',
    cost: '무료 (Edu License)',
    originalPrice: '$289',
    optimized: '전문 소프트웨어 개발 및 프로그래밍 교육',
    purpose: 'Java(IntelliJ), Python(PyCharm) 등 실습 환경 구축',
    method: 'Faculty 멤버로 신청 (학교 메일/ISIC-ITIC 카드)',
    tags: ['무료', '코딩', 'IDE'],
    url: 'https://www.jetbrains.com/community/education/#faculty',
    buttonText: '라이선스 발급'
  },
  {
    id: 'suno',
    name: 'Suno AI',
    category: 'other',
    educator: false,
    categoryLabel: '음악/오디오',
    cost: '$5/mo (Student)',
    originalPrice: '$10',
    optimized: 'AI 기반 음악 생성(작사/작곡/보컬)',
    purpose: '영상 BGM 제작, 창의적 음악 수업 보조',
    method: '주로 학생 대상 할인(변동 가능), 교육자는 별도 문의 추천',
    tags: ['할인', '음악', 'AI생성'],
    url: 'https://suno.com/',
    buttonText: '사이트 방문'
  },
  {
    id: 'wolfram',
    name: 'Wolfram Alpha',
    category: 'other',
    educator: true,
    educatorBadge: '교수/교사 가능',
    categoryLabel: '수학/과학',
    cost: '학술 할인 적용',
    originalPrice: '$9.99',
    optimized: '컴퓨테이셔널 인텔리전스 & 수식 계산',
    purpose: '복잡한 미적분, 데이터 시각화, 과학적 팩트 체크',
    method: '교육 기관 재직 증명으로 Academic Pricing 적용',
    tags: ['할인', '수학', '과학'],
    url: 'https://www.wolfram.com/wolfram-alpha-pro/pricing/academic/',
    buttonText: '할인 확인하기'
  },
  {
    id: 'prezi',
    name: 'Prezi',
    category: 'other',
    educator: true,
    educatorBadge: '교수/교사 가능',
    categoryLabel: '발표/편집',
    cost: '$3~$4/mo',
    originalPrice: 'EDU',
    optimized: '비선형적 스토리텔링 & 줌인/줌아웃 발표',
    purpose: '몰입도 높은 강의 자료 제작, 온라인 강의 녹화',
    method: '교육용 메일 인증으로 EDU Plus 플랜 가입',
    tags: ['할인', '발표', '수업'],
    url: 'https://prezi.com/education/',
    buttonText: '교육용 플랜 보기'
  },
  {
    id: 'brisk',
    name: 'Brisk Teaching',
    category: 'other',
    educator: true,
    educatorBadge: '교사 무료',
    categoryLabel: '교육/수업',
    cost: '무료',
    originalPrice: null,
    optimized: 'Google/Microsoft 통합 & 개인화된 학습 자료',
    purpose: '수업 자료 생성, 피드백 작성, Google Docs/Classroom 통합',
    method: '20,000개 이상 학군에서 사용, 교사 인증 후 무료',
    tags: ['무료', '교육', '통합'],
    url: 'https://www.briskteaching.com/',
    buttonText: '무료 시작하기'
  },
  {
    id: 'reclaim',
    name: 'Reclaim.ai',
    category: 'other',
    educator: true,
    educatorBadge: '교육 할인',
    categoryLabel: '생산성',
    cost: '50% 할인 (12개월)',
    originalPrice: 'Pro $12',
    optimized: 'AI 기반 일정 관리 & 자동 스케줄링',
    purpose: '교사 일정 최적화, 자동 회의 스케줄링, 시간 블록 관리',
    method: '교육 할인으로 12개월간 50% 할인',
    tags: ['할인', '생산성', '스케줄링'],
    url: 'https://reclaim.ai/pricing/education-discount',
    buttonText: '할인 확인하기'
  }
];
